In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("cleaned_merge_final.csv")

In [3]:
data.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_DELAY,ARRIVAL_DELAY,DIVERTED,CANCELLED,...,ORIGIN_AIRPORT_NAME,ORIGIN_CITY,ORIGIN_STATE,ORIGIN_LATITUDE,ORIGIN_LONGITUDE,DESTINATION_AIRPORT_NAME,DESTINATION_CITY,DESTINATION_STATE,DESTINATION_LATITUDE,DESTINATION_LONGITUDE
0,1,1,4,Alaska Airlines Inc.,ANC,SEA,-11.0,-22.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
1,1,1,4,Alaska Airlines Inc.,ANC,SEA,-4.0,-14.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
2,1,1,4,Alaska Airlines Inc.,ANC,SEA,NaN,NaN,0,1,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
3,1,1,4,Alaska Airlines Inc.,ANC,SEA,-15.0,-35.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
4,1,1,4,Alaska Airlines Inc.,ANC,SEA,-11.0,-12.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931

In [4]:
data_short = data.iloc[0:200, : ]

In [5]:
data_short.head()

,MONTH,DAY,DAY_OF_WEEK,AIRLINE,ORIGIN_AIRPORT,DESTINATION_AIRPORT,DEPARTURE_DELAY,ARRIVAL_DELAY,DIVERTED,CANCELLED,...,ORIGIN_AIRPORT_NAME,ORIGIN_CITY,ORIGIN_STATE,ORIGIN_LATITUDE,ORIGIN_LONGITUDE,DESTINATION_AIRPORT_NAME,DESTINATION_CITY,DESTINATION_STATE,DESTINATION_LATITUDE,DESTINATION_LONGITUDE
0,1,1,4,Alaska Airlines Inc.,ANC,SEA,-11.0,-22.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
1,1,1,4,Alaska Airlines Inc.,ANC,SEA,-4.0,-14.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
2,1,1,4,Alaska Airlines Inc.,ANC,SEA,NaN,NaN,0,1,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
3,1,1,4,Alaska Airlines Inc.,ANC,SEA,-15.0,-35.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931
4,1,1,4,Alaska Airlines Inc.,ANC,SEA,-11.0,-12.0,0,0,...,Ted Stevens Anchorage International Airport,Anchorage,AK,61.17432,-149.99619,Seattle-Tacoma International Airport,Seattle,WA,47.44898,-122.30931

In [6]:
len(data_short)

200

In [8]:
data_short.to_csv("test_flight.csv")

In [9]:
grouped_by_origin = data.groupby("ORIGIN_AIRPORT_NAME")